

export  const FETCHUSERNFO_SUCCESS='FETCHUSERNFO SUCCESS'
export   const FETCHUSERNFO_PROGRESS='FETCHUSERNFO PROGRESS'
export   const FETCHUSERNFO_FAILURE='FETCHUSERNFO SFAILURE'


export  const FETCHUSERPICS_SUCCESS='FETCHUSERPICS SUCCESS'
export   const FETCHUSERPICS_PROGRESS='FETCHUSERPICS PROGRESS'
export   const FETCHUSERPICS_FAILURE='FETCHUSERPICS FAILURE'
